"""Added draws in statistic model.

Revision ID: f132fc2f3be8
Revises: 127fc16e3f87
Create Date: 2024-08-15 16:42:07.783157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f132fc2f3be8'
down_revision = '127fc16e3f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draws', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_column('draws')

    # ### end Alembic commands ###
